/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    String getGreeting() {
        return "Runtime: Groovy ${GroovySystem.getVersion()} on ${System.getProperty('java.vm.name')} ${System.getProperty('java.runtime.version')}"
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
