/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    String getGreeting() {
        final list = new ArrayList<>()
        list << 'Runtime: Groovy'
        list << GroovySystem.getVersion()
        list << 'on'
        list << System.getProperty('java.vm.name')
        list << System.getProperty('java.runtime.version')
        return list.join(' ')
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
